/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hlavati;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Luka
 */
public class Prozor extends javax.swing.JFrame {

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObojaj = new javax.swing.JButton();
        btnOcisti = new javax.swing.JButton();
        btnPromjeniText = new javax.swing.JButton();
        lblText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnObojaj.setText("Obojaj text");
        btnObojaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnObojajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnObojajMouseExited(evt);
            }
        });
        btnObojaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObojajActionPerformed(evt);
            }
        });

        btnOcisti.setText("Ocisti text");
        btnOcisti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOcistiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOcistiMouseExited(evt);
            }
        });
        btnOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiActionPerformed(evt);
            }
        });

        btnPromjeniText.setText("Promjeni text");
        btnPromjeniText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPromjeniTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPromjeniTextMouseExited(evt);
            }
        });
        btnPromjeniText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniTextActionPerformed(evt);
            }
        });

        lblText.setText("Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnObojaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOcisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPromjeniText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnPromjeniText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObojaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOcisti)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromjeniTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniTextActionPerformed
        lblText.setText(JOptionPane.showInputDialog("Unesite novi text"));
    }//GEN-LAST:event_btnPromjeniTextActionPerformed

    private void btnPromjeniTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniTextMouseEntered
        btnPromjeniText.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnPromjeniTextMouseEntered

    private void btnObojajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObojajMouseEntered
        btnObojaj.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnObojajMouseEntered

    private void btnOcistiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcistiMouseEntered
        btnOcisti.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnOcistiMouseEntered

    private void btnPromjeniTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromjeniTextMouseExited
        btnPromjeniText.setBackground(btnObojaj.getBackground());
    }//GEN-LAST:event_btnPromjeniTextMouseExited

    private void btnObojajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObojajMouseExited
        btnObojaj.setBackground(btnPromjeniText.getBackground());
    }//GEN-LAST:event_btnObojajMouseExited

    private void btnOcistiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcistiMouseExited
        btnOcisti.setBackground(btnPromjeniText.getBackground());
    }//GEN-LAST:event_btnOcistiMouseExited

    private void btnObojajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObojajActionPerformed
        if(lblText.getForeground() == Color.GREEN){
            lblText.setForeground(Color.BLACK);
        } else {
            lblText.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_btnObojajActionPerformed

    private void btnOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiActionPerformed
        lblText.setText("");
    }//GEN-LAST:event_btnOcistiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObojaj;
    private javax.swing.JButton btnOcisti;
    private javax.swing.JButton btnPromjeniText;
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
}
